### ISSUE TITLE
Download of HTML files is not ideal

### ISSUE THREAD

**Issue by brianhenk** [brianhenk/tritun-downloader#3]
Service manuals are comprised of hundreds of small HTML files. Each references external content and doesn't render correctly when downloaded. Instead, a single HTML file should be created that includes all the content and downloads with references to local files.

**Comment by brianhenk** [comment]
This was addressed after https://github.com/brianhenk/tritun-downloader/commit/6d56dee091dccd2494cc035883b3825432c8f6f5

**Comment by pme1** [comment]
hi, FYI used the addon recently, unfortunately it does not manage page breaks well and text/diagrams are split across the break, not just me apparently

**Comment by brianhenk** [comment]
This is a fair criticism, but unfortunately, this issue is caused by Firefox itself. 

The HTML that the extension renders has no explicit page breaks built-in. those are created based on the paper size you're actually printing to (or simulating if printing to PDF). Firefox seems to insert page breaks haphazardlly. I actually save the final HTML file as "Web Page, Complete) rather than print it. Then I either browse it offline or print from Chrome, which seems to do a better job.
