### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Pachulero** [brianhenk/tritun-downloader#5]
the download button is not activated. maybe the web site is updated

**Comment by sejtam** [comment]
Same here. I see no Download Icon but under the '...' in the URL bar there is a 'Download all'. one which stays greyed out whatever I do.

Name 	Firefox
Version 	74.0
Build ID 	20200309095159
Update Folder 	
/Users/mathias/Library/Caches/Mozilla/updates/Applications/Firefox
Update History 	
Update Channel 	release
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:74.0) Gecko/20100101 Firefox/74.0
OS 	Darwin 19.3.0
Application Binary 	/Applications/Firefox.app/Contents/MacOS/firefox
Profile Folder 	
/Users/mathias/Library/Application Support/Firefox/Profiles/gxzkcm3o.default
Enabled Plugins 	about:plugins
Build Configuration 	about:buildconfig
Memory Use 	about:memory
Performance 	about:performance
Registered Service Workers 	about:serviceworkers
Multiprocess Windows 	1/1 Enabled by default
Remote Processes 	4
Enterprise Policies 	Inactive
Google Location Service Key 	Found
Google Safebrowsing Key 	Found
Mozilla Location Service Key 	Found
Safe Mode 	false
Profiles 	about:profiles

Firefox Features
Name 	Version 	ID
DoH Roll-Out	1.3.0	doh-rollout@mozilla.org
Firefox Screenshots	39.0.0	screenshots@mozilla.org
Form Autofill	1.0	formautofill@mozilla.org
Web Compat	7.0.0	webcompat@mozilla.org
WebCompat Reporter	1.1.0	webcompat-reporter@mozilla.org
Remote Processes
Type 	Count
Web Content	3 / 8
Extension	1
Extensions
Name 	Version 	Enabled 	ID
1Password extension (desktop app required)	4.7.5.90	true	onepassword4@agilebits.com
Adblock Plus - free ad blocker	3.8	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Amazon.co.uk	1.1	true	amazon@search.mozilla.org
Bing	1.1	true	bing@search.mozilla.org
Chambers (UK)	1.0	true	chambers-en-GB@search.mozilla.org
ColorfulTabs	34.3	true	{0545b830-f0aa-4d7e-8820-50a4629a56fe}
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
F.B Purity - Cleans up Facebook (WX)	23.0.1.0	true	fbpElectroWebExt@fbpurity.com
Google	1.0	true	google@search.mozilla.org
TriTun Downloader	1.1	true	{386a58c1-13e0-47ee-9ab5-29198fd95444}
Twitter	1.0	true	twitter@search.mozilla.org
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
NoScript	11.0.17	false	{73a6fe31-595d-460b-a920-fcc0f8843232}

**Comment by sejtam** [comment]
In the inspetor I see: 

This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. view
Ignoring unsupported entryTypes: paint. view:171:14703
No valid entryTypes; aborting registration. view:171:14703
Ignoring unsupported entryTypes: largest-contentful-paint. view:171:14737
No valid entryTypes; aborting registration. view:171:14737
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. 2186
Loading failed for the <script> with source “https://js-agent.newrelic.com/nr-1167.min.js”.

But i don't see any attempt to load that newlic script (no request)

**Comment by brianhenk** [comment]
Sorry I never was able to review and fix this. Closing because the site is now completely different (TriTun is replaced wtih TTI).
