### ISSUE TITLE
No Download Icon showing

### ISSUE THREAD

**Issue by YnnMth** [brianhenk/tritun-downloader#6]
Hi!

Just letting you guys know that today, it ain't working on April 11th. Can't get the icon pop-up neither.

![issue](https://user-images.githubusercontent.com/63495271/79040018-c9b48680-7be5-11ea-91a7-c5fa3ab3ab6f.png)

**Comment by asmetana** [comment]
Same here, just tried today.

**Comment by cembry26** [comment]
Still an issue

**Comment by brianhenk** [comment]
Sorry I never was able to review and fix this. Closing because the site is now completely different (TriTun is replaced wtih TTI).
